-- Todos os registros abaixo são fictícios e demonstrativos. Não cria contatos.
insert into public.practice_areas(slug,name,description,is_published,sort_order) values
('direito-trabalhista','Direito Trabalhista','Orientação jurídica sobre relações de trabalho.',true,1),('direito-de-familia','Direito de Família','Orientação em questões familiares.',true,2),('direito-previdenciario','Direito Previdenciário','Orientação sobre benefícios e aposentadorias.',true,3),('direito-empresarial','Direito Empresarial','Assessoria jurídica para empresas.',true,4) on conflict(slug) do nothing;
insert into public.team_members(slug,name,role,practice_area,oab_placeholder,is_published,sort_order) values
('mariana-ferraz','Mariana Ferraz','Sócia-fundadora','Direito de Família e Sucessões','OAB/UF 00.000 — DEMO',true,1),('ricardo-oliveira','Ricardo Oliveira','Sócio','Direito Trabalhista','OAB/UF 00.000 — DEMO',true,2),('helena-martins','Helena Martins','Sócia','Direito Previdenciário','OAB/UF 00.000 — DEMO',true,3),('gustavo-almeida','Gustavo Almeida','Advogado associado','Direito Empresarial','OAB/UF 00.000 — DEMO',true,4) on conflict(slug) do nothing;
insert into public.articles(slug,category,title,summary,body_markdown,author_name,status,published_at) values
('fui-demitido-verbas-rescisao','Direito Trabalhista','Fui demitido: quais verbas podem fazer parte da rescisão?','Introdução informativa.','Conteúdo demonstrativo.','Equipe editorial','published',now()),('como-funciona-guarda-compartilhada','Direito de Família','Como funciona a guarda compartilhada?','Introdução informativa.','Conteúdo demonstrativo.','Equipe editorial','published',now()),('modalidades-de-aposentadoria','Direito Previdenciário','Quais são as principais modalidades de aposentadoria?','Introdução informativa.','Conteúdo demonstrativo.','Equipe editorial','published',now()),('contratos-reduzem-riscos','Direito Empresarial','Por que contratos bem elaborados reduzem riscos empresariais?','Introdução informativa.','Conteúdo demonstrativo.','Equipe editorial','published',now()) on conflict(slug) do nothing;
insert into public.faq_items(question,answer,category,is_published,sort_order) select * from(values
('Como funciona o primeiro atendimento?','A equipe recebe um resumo e informa os próximos passos.','Atendimento',true,1),('O escritório realiza atendimento online?','Sim, conforme disponibilidade.','Atendimento online',true,2),('Quais informações devo enviar inicialmente?','Somente dados mínimos e resumo.','Privacidade',true,3),('Preciso enviar documentos no primeiro contato?','Não. Aguarde orientação.','Documentos',true,4),('O envio cria relação advogado-cliente?','Não, depende de formalização.','Consulta',true,5),('Como os dados serão utilizados?','Para responder e organizar o atendimento.','Privacidade',true,6),('Em quais áreas o escritório atua?','Trabalhista, Família, Previdenciário e Empresarial.','Áreas',true,7),('Como saber se podem analisar meu caso?','Envie um resumo pelos canais oficiais.','Consulta',true,8)) as v(question,answer,category,is_published,sort_order);
insert into public.site_settings(key,value,is_critical) values('demo_mode','{"enabled":true}'::jsonb,true),('retention','{"review_days":180,"automatic_deletion":false}'::jsonb,true) on conflict(key) do nothing;
