"use client";
import { useEffect, useState } from "react";
type Locale = "pt-BR" | "en-US";
const translations: Record<string, string> = {
  "Início":"Home","O Escritório":"The Firm","Áreas de Atuação":"Practice Areas","Equipe":"Team","Conteúdos":"Insights","Contato":"Contact","Fale pelo WhatsApp":"Chat on WhatsApp",
  "Atendimento presencial e online":"In-person and online service","Experiência jurídica para proteger seus direitos e orientar suas decisões":"Legal experience to protect your rights and guide your decisions","Há mais de uma década oferecendo orientação jurídica com clareza, responsabilidade e segurança para pessoas, famílias e empresas.":"For over a decade, providing clear, responsible and reliable legal guidance to individuals, families and businesses.",
  "Fale com nossa equipe":"Talk to our team","Conheça nossas áreas":"Explore our practice areas","+10 anos":"10+ years","de experiência jurídica":"of legal experience","Presencial e online":"In-person and online","atendimento de onde você estiver":"service wherever you are","Retorno inicial ágil":"Prompt initial response","durante o horário de atendimento":"during business hours","Atuação regional":"Regional practice","conhecimento próximo da realidade local":"close knowledge of the local context",
  "O escritório":"The firm","Experiência, estratégia e proximidade":"Experience, strategy and proximity","Conheça nossa história":"Discover our story","Áreas de atuação":"Practice areas","Orientação integrada em diferentes momentos":"Integrated guidance for every stage","Direito Trabalhista":"Employment Law","Direito de Família":"Family Law","Direito Previdenciário":"Social Security Law","Direito Empresarial":"Business Law","Saiba mais":"Learn more",
  "Como funciona nosso atendimento":"How our service works","Entre em contato":"Get in touch","Conte sua necessidade":"Tell us what you need","Análise inicial":"Initial assessment","Orientação":"Guidance","Nossa equipe":"Our team","Atuação multidisciplinar e próxima":"A multidisciplinary and accessible team","Ver perfil →":"View profile →","Conteúdos jurídicos":"Legal insights","Informação clara para decisões conscientes":"Clear information for informed decisions","Ler artigo →":"Read article →","Ver todos os conteúdos":"View all insights",
  "Precisa de orientação jurídica?":"Need legal guidance?","Fale com o escritório":"Contact the firm","Iniciar conversa":"Start a conversation","Envie uma mensagem":"Send a message","Nome":"Name","E-mail":"Email","Telefone":"Phone","Assunto":"Subject","Selecione":"Select","Mensagem":"Message","Enviar mensagem":"Send message","Ficou com alguma dúvida?":"Still have questions?","Tirar dúvida pelo WhatsApp":"Ask via WhatsApp","Ver perguntas frequentes":"View frequently asked questions",
  "Navegação":"Navigation","Áreas":"Practice areas","Informações legais":"Legal information","Política de Privacidade":"Privacy Policy","Política de Cookies":"Cookie Policy","Termos de Uso":"Terms of Use","Aviso Legal":"Legal Notice",
  "A Auréa Advocacia oferece suporte jurídico a pessoas, famílias e empresas com escuta atenta, estratégia e comunicação clara. Nossa equipe reúne profissionais com atuação em diferentes áreas do Direito, trabalhando de forma integrada para compreender cada situação e apresentar caminhos jurídicos adequados.":"Auréa Advocacia supports individuals, families and businesses with attentive listening, strategy and clear communication. Our multidisciplinary team works collaboratively to understand each situation and identify appropriate legal paths.",
  "Com estrutura moderna, oferecemos atendimento presencial e online, priorizando comunicação clara, responsabilidade profissional e acompanhamento cuidadoso.":"With a modern structure, we provide in-person and online service, prioritizing clear communication, professional responsibility and attentive follow-up.",
  "Orientação jurídica sobre relações de trabalho, contratos, verbas rescisórias, direitos de trabalhadores e questões empresariais trabalhistas.":"Legal guidance on employment relationships, contracts, termination payments, employee rights and business employment matters.",
  "Atuação em divórcio, guarda, pensão alimentícia, união estável, inventário e outras questões familiares.":"Guidance on divorce, custody, child support, civil partnerships, probate and other family matters.",
  "Orientação sobre aposentadorias, benefícios previdenciários, revisões e requerimentos administrativos.":"Guidance on retirement, social security benefits, reviews and administrative applications.",
  "Assessoria jurídica para empresas, elaboração de contratos, prevenção de riscos e resolução de conflitos societários.":"Legal counsel for businesses, contract drafting, risk prevention and corporate dispute resolution.",
  "Fale conosco pelo WhatsApp ou formulário.":"Contact us through WhatsApp or the form.","Apresente brevemente a situação e a orientação procurada.":"Briefly describe your situation and the guidance you are seeking.","A equipe verifica as informações e identifica próximos passos possíveis.":"Our team reviews the information and identifies possible next steps.","Você recebe informações sobre a forma adequada de prosseguir.":"You receive information on the appropriate way to proceed.",
  "Sócia-fundadora":"Founding partner","Sócio":"Partner","Sócia":"Partner","Advogado associado":"Associate lawyer","Direito de Família e Sucessões":"Family and Succession Law",
  "Fui demitido: quais verbas podem fazer parte da rescisão?":"I was dismissed: which payments may be included in my termination?","Como funciona a guarda compartilhada?":"How does shared custody work?","Quais são as principais modalidades de aposentadoria?":"What are the main types of retirement?","Por que contratos bem elaborados reduzem riscos empresariais?":"Why do well-drafted contracts reduce business risks?",
  "Conheça alguns dos pagamentos que podem ser considerados em uma rescisão trabalhista, conforme o tipo de desligamento.":"Learn about payments that may apply to an employment termination depending on the type of dismissal.","Entenda os aspectos gerais da divisão de responsabilidades parentais após uma separação.":"Understand the general aspects of shared parental responsibilities after separation.","Veja uma introdução às modalidades previdenciárias e à importância da análise individual dos requisitos.":"An introduction to retirement options and the importance of reviewing individual requirements.","Entenda como contratos claros ajudam a organizar obrigações e prevenir conflitos.":"Understand how clear contracts help organize obligations and prevent disputes.",
  "Entre em contato com nossa equipe para apresentar sua necessidade e obter informações sobre a forma de atendimento do escritório.":"Contact our team to describe your needs and learn how the firm can assist you.","Segunda a sexta, das 8h às 18h":"Monday to Friday, 8 a.m. to 6 p.m.","Li e aceito a":"I have read and accept the","O aceite é obrigatório.":"Acceptance is required.",
  "Não envie senhas, dados bancários, documentos sigilosos ou informações pessoais sensíveis. O envio não estabelece automaticamente relação advogado-cliente.":"Do not send passwords, banking information, confidential documents or sensitive personal data. Submitting this form does not automatically establish an attorney-client relationship.",
  "Nossa equipe está disponível para explicar como funciona o atendimento e indicar o canal adequado para sua necessidade.":"Our team is available to explain how our service works and direct you to the appropriate channel.","Para preservar sua privacidade, evite encaminhar informações sensíveis no primeiro contato.":"To protect your privacy, avoid sharing sensitive information in your first contact.","Atuação jurídica responsável para pessoas, famílias e empresas.":"Responsible legal counsel for individuals, families and businesses.","As informações apresentadas neste site possuem caráter exclusivamente informativo e não substituem orientação jurídica individual.":"The information on this website is for general informational purposes and does not replace individual legal advice.","Dúvidas":"Questions"
};
const originals = new WeakMap<Text,string>();
function translatePage(locale:Locale){document.documentElement.lang=locale;const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node=walker.nextNode() as Text|null;while(node){const parent=node.parentElement;if(parent&&!['SCRIPT','STYLE','NOSCRIPT'].includes(parent.tagName)){if(!originals.has(node))originals.set(node,node.nodeValue??'');const original=originals.get(node)??'';const trimmed=original.trim();const translated=translations[trimmed];node.nodeValue=locale==='en-US'&&translated?original.replace(trimmed,translated):original}node=walker.nextNode() as Text|null}}
export function LanguageSwitcher(){const[locale,setLocale]=useState<Locale>('pt-BR');useEffect(()=>{const saved=localStorage.getItem('site-locale');if(saved==='en-US')setLocale(saved)},[]);useEffect(()=>{translatePage(locale)},[locale]);function choose(next:Locale){localStorage.setItem('site-locale',next);setLocale(next)}return <div className="language-switcher" role="group" aria-label="Selecionar idioma"><button type="button" className={locale==='pt-BR'?'selected':''} aria-pressed={locale==='pt-BR'} aria-label="Português do Brasil" title="Português do Brasil" onClick={()=>choose('pt-BR')}><span className="flag flag-br" aria-hidden="true"/><span className="language-code">PT</span></button><button type="button" className={locale==='en-US'?'selected':''} aria-pressed={locale==='en-US'} aria-label="English (United States)" title="English (United States)" onClick={()=>choose('en-US')}><span className="flag flag-us" aria-hidden="true"/><span className="language-code">EN</span></button></div>}
